# Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [9]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr1

array([1, 2, 3, 4, 5])

# Properties & Attributes

1. Shape
2. nDim
3. Size
4. ItemSize
5. Dtype
6. astype()

In [12]:
arr1.shape

(5,)

In [13]:
arr2.shape

(2, 3)

In [14]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
arr9.shape

(2, 2, 2)

In [17]:
arr9.ndim

3

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.ndim

2

In [20]:
arr1.ndim

1

In [21]:
arr1.size

5

In [22]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
arr9.size

8

In [24]:
arr9.itemsize

4

In [25]:
arr8.itemsize

8

In [26]:
arr8.dtype

dtype('float64')

In [27]:
arr9.dtype

dtype('int32')

In [28]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [29]:
lista=range(100)
arr11=np.arange(100)

In [30]:
import sys

In [31]:
print(sys.getsizeof(87)*len(lista))

2800


In [32]:
print(arr11.itemsize*arr11.size)

400


In [33]:
import time

In [34]:
x=range(100000)
y=range(100000, 200000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.0680077075958252


In [36]:
a=np.arange(100000)
b=np.arange(100000,200000)

start_time=time.time()
c=a+b

print(time.time()-start_time)

0.001001119613647461


In [41]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arr12[2]

array([ 8,  9, 10, 11])

## Print 3rd Column

In [44]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

## Print 3rd and 4th column

In [45]:
arr12[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [51]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr12[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [53]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
arr12[4:6, 2:4]

array([[18, 19],
       [22, 23]])

In [55]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [56]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [57]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
