In [1]:
import numpy as np

In [2]:
arr8=np.arange(24).reshape(6,4)

In [4]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Find 1st row 3rd row and 5th row

## Fancy Indexing

In [5]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [28]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[24, 79, 25, 31, 70],
       [86, 96, 49, 27, 63],
       [67, 49, 93, 23, 46],
       [ 5, 46, 67, 46, 92]])

In [30]:
arr[0][2]

25

In [31]:
arr>50

array([[False,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True, False,  True, False, False],
       [False, False,  True, False,  True]])

## Indexing using Boolean array

In [32]:
arr[arr>50]

array([79, 70, 86, 96, 63, 67, 93, 67, 92])

In [33]:
arr[(arr>50) & (arr%2!=0)]

array([79, 63, 67, 93, 67])

## Put 0 which is >50 and odd 

In [34]:
arr[(arr>50) & (arr%2!=0)]=0

In [35]:
arr

array([[24,  0, 25, 31, 70],
       [86, 96, 49, 27,  0],
       [ 0, 49,  0, 23, 46],
       [ 5, 46,  0, 46, 92]])