In [1]:
import numpy as np

In [37]:
np.random.random()

0.7203244934421581

In [40]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [15]:
np.random.uniform(1,100)

15.528833190894192

In [17]:
np.random.uniform(1,100,10).reshape(2,5)

array([[67.37628351, 42.31317543, 56.31029302, 14.89830692, 20.61204742],
       [80.2737123 , 96.857896  , 32.02899364, 69.53993895, 87.76252608]])

In [23]:
np.random.randint(1,10,15).reshape(3,5)

array([[6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8]])

In [28]:
a=np.random.randint(1,10,6)
a

array([9, 7, 5, 6, 7, 3])

In [29]:
np.max(a)

9

In [30]:
np.min(a)

3

In [32]:
a[np.argmax(a)]

9

In [33]:
a[np.argmin(a)]

3

In [34]:
np.argmin(a)

5

In [35]:
a[a%2==1]=-1
a

array([-1, -1, -1,  6, -1, -1])

In [43]:
a=np.random.randint(1,50,6)
a

array([ 7, 26, 21, 38, 19, 21])

In [44]:
np.where(a%2==1,-1,a)

array([-1, 26, -1, 38, -1, -1])

In [45]:
out=np.where(a%2==1,-1,a)
out

array([-1, 26, -1, 38, -1, -1])

In [46]:
a=np.random.randint(1,50,10)
a

array([12, 43, 29, 30, 15,  5, 24, 24, 42, 31])

In [48]:
a=np.sort(a)
a

array([ 5, 12, 15, 24, 24, 29, 30, 31, 42, 43])

In [49]:
np.percentile(a,25)

17.25

In [50]:
np.percentile(a,50)

26.5

In [51]:
np.percentile(a,99.8)

42.982